### ISSUE TITLE
Uses the wrong registry HKEY_LOCAL_MACHINE. 

### ISSUE THREAD

**Issue by Radulfr4** [kgersen/allegice#17]

**Comment by kgersen** [comment]
more details plz.

**Comment by Radulfr4** [comment]
You may have already fixed this. 

HKEY_LOCAL_MACHINE is the old registry. HKCU is currently used. Check that if you want to see if Allegiance is installed. 
I had to mess with my registry to get a download of this to work.

**Comment by kgersen** [comment]
fixed in code. will wait on #19 for release.
